spring.application.name=tp6-7
server.port=8090
# TEST
# http://localhost:8090/test/popular
# http://localhost:8090/test/film/875828
# http://localhost:8090/films

# Configuration of the SGBD SQLite
spring.datasource.url=jdbc:sqlite:db/sites.db
spring.datasource.driver-class-name=org.sqlite.JDBC
spring.datasource.username=
spring.datasource.password=
# Configuration of Hibernate
spring.jpa.databaseplatform=org.hibernate.community.dialect.SQLiteDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# Configuration TMDB
tmdb.api-key=db44800cadd0baa04905bac6251520e1
tmdb.base-url=https://api.themoviedb.org/3

# docs
# https://developer.themoviedb.org/